"""Monte-Carlo simulation-based correlation tests.

Implements simulation-based power for correlation tests:

* "Pearson's Correlation Tests (Simulation)"          (Chapter 802)
* "Spearman's Rank Correlation Tests (Simulation)"    (Chapter 803)
* "Kendall's Tau-b Correlation Tests (Simulation)"    (Chapter 804)
* "Power Comparison of Correlation Tests (Simulation)" (Chapter 805)

Each test draws ``n_sims`` bivariate (X, Y) replicates of size ``n`` with a
target population product-moment correlation ``r``, computes the relevant
sample correlation statistic on each replicate, and reports the rejection
proportion as the simulated power.

The bivariate generator handles the four marginal distribution families
supported by the project's ``variances_simulation`` module — ``normal``,
``t``, ``uniform``, ``exponential`` — via the Gaussian-copula construction:
two correlated standard normals are drawn with correlation ``r`` and then
each marginal is mapped through ``Phi`` and the inverse CDF of the target
marginal. For the bivariate normal case this reduces to the standard
Cholesky construction. Note that for non-Gaussian marginals the realised
Pearson correlation of (X, Y) drifts slightly from the input ``r`` because
the copula correlation is preserved on the latent (Z1, Z2) scale, not on
the transformed scale. Note that "results
using the bivariate normal option will be slightly different from those
obtained when a custom model with two normal distributions is used".

When solving for sample size, an outer bisection brackets the smallest
``n`` that achieves the requested power.

Results are *stochastic*: with the default ``n_sims=10000`` the binomial
95% CI around a true power of 0.5 is ~+/-0.010 and ~+/-0.004 around
0.95. Fixtures therefore
use a wider tolerance (~+/-0.015 absolute on power) than analytic
methods. All simulations seed ``numpy.random`` (default ``seed=42``) for
deterministic reproducibility under a fixed test harness.
"""
from __future__ import annotations

import math
from typing import Any

import numpy as np
from scipy import stats


_SUPPORTED_DISTS = ("normal", "t", "uniform", "exponential")


# ---------------------------------------------------------------------------
# Bivariate sampler with marginals and target latent correlation
# ---------------------------------------------------------------------------


def _sample_bivariate(
    rng: np.random.Generator,
    *,
    n: int,
    n_sims: int,
    r: float,
    dist_x: str,
    dist_y: str,
    df_x: float | None = None,
    df_y: float | None = None,
) -> tuple[np.ndarray, np.ndarray]:
    """Draw ``n_sims`` replicates of paired (X, Y) of size ``n``.

    Bivariate normals (Z1, Z2) are generated by Cholesky with correlation
    ``r``; if either marginal is non-normal the corresponding Z is mapped
    through Phi to a uniform and then through the inverse CDF of the
    target marginal. All marginals are standardised to unit variance so
    that ``r`` corresponds to the *target* Pearson correlation on the
    underlying Gaussian latent (the realised Pearson correlation of
    (X, Y) drifts slightly for non-normal marginals).
    """
    if not -1.0 < r < 1.0:
        raise ValueError("r must lie strictly within (-1, 1)")
    if dist_x not in _SUPPORTED_DISTS:
        raise ValueError(f"unsupported dist_x={dist_x!r}; choose {_SUPPORTED_DISTS}")
    if dist_y not in _SUPPORTED_DISTS:
        raise ValueError(f"unsupported dist_y={dist_y!r}; choose {_SUPPORTED_DISTS}")

    z1 = rng.standard_normal(size=(n_sims, n))
    z_indep = rng.standard_normal(size=(n_sims, n))
    z2 = r * z1 + math.sqrt(1.0 - r * r) * z_indep

    def _transform(z: np.ndarray, dist: str, df: float | None) -> np.ndarray:
        if dist == "normal":
            return z
        u = stats.norm.cdf(z)
        # clip to avoid +/-inf in inverse CDF
        u = np.clip(u, 1e-12, 1.0 - 1e-12)
        if dist == "t":
            if df is None or df <= 2:
                raise ValueError("t marginal requires df > 2 for finite variance")
            t = stats.t.ppf(u, df=df)
            scale = math.sqrt(df / (df - 2.0))
            return t / scale
        if dist == "uniform":
            # Uniform on [-sqrt(3), sqrt(3)] has variance 1.
            return (2 * u - 1.0) * math.sqrt(3.0)
        if dist == "exponential":
            # Exp(1) - 1: zero mean, unit variance.
            return -np.log(1.0 - u) - 1.0
        raise ValueError(f"unsupported dist {dist!r}")

    x = _transform(z1, dist_x, df_x)
    y = _transform(z2, dist_y, df_y)
    return x, y


# ---------------------------------------------------------------------------
# Vectorised sample correlation statistics
# ---------------------------------------------------------------------------


def _pearson_r(x: np.ndarray, y: np.ndarray) -> np.ndarray:
    xm = x - x.mean(axis=1, keepdims=True)
    ym = y - y.mean(axis=1, keepdims=True)
    num = (xm * ym).sum(axis=1)
    den = np.sqrt((xm ** 2).sum(axis=1) * (ym ** 2).sum(axis=1))
    den = np.where(den <= 0, np.finfo(float).tiny, den)
    return num / den


def _pearson_pvalue(r: np.ndarray, n: int, rho0: float, sides: int) -> np.ndarray:
    """Two- or one-sided Pearson correlation test p-value.

    For ``rho0 == 0`` the exact null reference is the Student t with
    ``n - 2`` df via ``t = r * sqrt(n-2) / sqrt(1-r^2)``.

    For ``rho0 != 0`` the Fisher z-transform is used: under H0,
    ``z = arctanh(r)`` is approximately Normal(arctanh(rho0), 1/(n-3)).
    """
    if rho0 == 0.0:
        r2 = np.clip(r * r, 0.0, 1.0 - 1e-30)
        t = r * np.sqrt(n - 2) / np.sqrt(1.0 - r2)
        if sides == 2:
            return 2.0 * (1.0 - stats.t.cdf(np.abs(t), df=n - 2))
        # one-sided rejects when r > critical (positive tail by convention)
        return 1.0 - stats.t.cdf(t, df=n - 2)
    # Fisher z
    r_c = np.clip(r, -0.999999999, 0.999999999)
    z = 0.5 * np.log((1.0 + r_c) / (1.0 - r_c))
    z0 = 0.5 * math.log((1.0 + rho0) / (1.0 - rho0))
    se = 1.0 / math.sqrt(n - 3)
    stat = (z - z0) / se
    if sides == 2:
        return 2.0 * (1.0 - stats.norm.cdf(np.abs(stat)))
    return 1.0 - stats.norm.cdf(stat)


def _spearman_rho(x: np.ndarray, y: np.ndarray) -> np.ndarray:
    rx = stats.rankdata(x, axis=1)
    ry = stats.rankdata(y, axis=1)
    return _pearson_r(rx, ry)


def _spearman_pvalue(rho: np.ndarray, n: int, sides: int) -> np.ndarray:
    """Spearman p-value via the Student-t approximation
    ``t = rho * sqrt(n-2) / sqrt(1-rho^2)``, df = n-2 (Kendall & Gibbons 1990).
    """
    r2 = np.clip(rho * rho, 0.0, 1.0 - 1e-30)
    t = rho * np.sqrt(n - 2) / np.sqrt(1.0 - r2)
    if sides == 2:
        return 2.0 * (1.0 - stats.t.cdf(np.abs(t), df=n - 2))
    return 1.0 - stats.t.cdf(t, df=n - 2)


def _kendall_tau(x: np.ndarray, y: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Vectorised Kendall tau-b plus tie counts (n1, n2) for the pair-tied
    pairs in x and y respectively.

    Returns ``(tau, n1, n2)``.
    """
    n_sims, n = x.shape
    i_idx, j_idx = np.triu_indices(n, k=1)
    sx = np.sign(x[:, j_idx] - x[:, i_idx])
    sy = np.sign(y[:, j_idx] - y[:, i_idx])
    C_minus_D = (sx * sy).sum(axis=1)
    n1 = (sx == 0).sum(axis=1)
    n2 = (sy == 0).sum(axis=1)
    N0 = n * (n - 1) / 2.0
    den = np.sqrt(np.maximum((N0 - n1) * (N0 - n2), np.finfo(float).tiny))
    return C_minus_D / den, n1, n2


def _kendall_pvalue(tau: np.ndarray, n: int, sides: int) -> np.ndarray:
    """Kendall tau-b p-value via the normal approximation
    ``Var(tau) = 2(2n+5) / (9 n (n-1))``.
    """
    var = 2.0 * (2.0 * n + 5.0) / (9.0 * n * (n - 1))
    z = tau / math.sqrt(var)
    if sides == 2:
        return 2.0 * (1.0 - stats.norm.cdf(np.abs(z)))
    return 1.0 - stats.norm.cdf(z)


# ---------------------------------------------------------------------------
# Simulation core
# ---------------------------------------------------------------------------


_TEST_FNS = {"pearson", "spearman", "kendall"}


def _validate_inputs(
    r: float,
    rho0: float,
    alpha: float,
    sides: int,
    dist_x: str,
    dist_y: str,
) -> None:
    if not -1.0 < r < 1.0:
        raise ValueError("r must be strictly within (-1, 1)")
    if not -1.0 < rho0 < 1.0:
        raise ValueError("rho0 must be strictly within (-1, 1)")
    if not 0.0 < alpha < 1.0:
        raise ValueError("alpha must be in (0, 1)")
    if sides not in (1, 2):
        raise ValueError("sides must be 1 or 2")
    if dist_x not in _SUPPORTED_DISTS:
        raise ValueError(f"unsupported dist_x={dist_x!r}")
    if dist_y not in _SUPPORTED_DISTS:
        raise ValueError(f"unsupported dist_y={dist_y!r}")


def _simulate_power(
    *,
    test: str,
    n: int,
    r: float,
    rho0: float,
    dist_x: str,
    dist_y: str,
    df_x: float | None,
    df_y: float | None,
    alpha: float,
    sides: int,
    n_sims: int,
    seed: int,
) -> float:
    rng = np.random.default_rng(seed)
    x, y = _sample_bivariate(
        rng, n=n, n_sims=n_sims, r=r,
        dist_x=dist_x, dist_y=dist_y, df_x=df_x, df_y=df_y,
    )
    if test == "pearson":
        r_hat = _pearson_r(x, y)
        p = _pearson_pvalue(r_hat, n, rho0, sides)
    elif test == "spearman":
        rho_hat = _spearman_rho(x, y)
        p = _spearman_pvalue(rho_hat, n, sides)
    elif test == "kendall":
        tau_hat, _, _ = _kendall_tau(x, y)
        p = _kendall_pvalue(tau_hat, n, sides)
    else:
        raise ValueError(f"unknown test {test!r}")
    return float(np.mean(p < alpha))


def _simulate_all_three(
    *,
    n: int,
    r: float,
    rho0: float,
    dist_x: str,
    dist_y: str,
    df_x: float | None,
    df_y: float | None,
    alpha: float,
    sides: int,
    n_sims: int,
    seed: int,
) -> dict[str, float]:
    """Run all three correlation tests on the *same* simulated data and
    report the rejection proportion for each.
    """
    rng = np.random.default_rng(seed)
    x, y = _sample_bivariate(
        rng, n=n, n_sims=n_sims, r=r,
        dist_x=dist_x, dist_y=dist_y, df_x=df_x, df_y=df_y,
    )
    r_hat = _pearson_r(x, y)
    rho_hat = _spearman_rho(x, y)
    tau_hat, _, _ = _kendall_tau(x, y)
    return {
        "pearson_power": float(np.mean(_pearson_pvalue(r_hat, n, rho0, sides) < alpha)),
        "spearman_power": float(np.mean(_spearman_pvalue(rho_hat, n, sides) < alpha)),
        "kendall_power": float(np.mean(_kendall_pvalue(tau_hat, n, sides) < alpha)),
    }


def _bisect_n(
    *,
    test: str,
    r: float,
    rho0: float,
    dist_x: str,
    dist_y: str,
    df_x: float | None,
    df_y: float | None,
    alpha: float,
    sides: int,
    target_power: float,
    n_sims: int,
    seed: int,
    n_min: int = 5,
    n_max: int = 5000,
) -> tuple[int, float]:
    if not 0.0 < target_power < 1.0:
        raise ValueError("power must be in (0, 1)")

    def power_at(n: int) -> float:
        return _simulate_power(
            test=test, n=n, r=r, rho0=rho0,
            dist_x=dist_x, dist_y=dist_y, df_x=df_x, df_y=df_y,
            alpha=alpha, sides=sides, n_sims=n_sims, seed=seed,
        )

    lo = n_min
    hi = max(n_min, 16)
    p_hi = power_at(hi)
    while p_hi < target_power:
        lo = hi
        hi = hi * 2
        if hi > n_max:
            raise RuntimeError(
                f"failed to bracket n within {n_max}; last power={p_hi:.3f}"
            )
        p_hi = power_at(hi)

    while lo + 1 < hi:
        mid = (lo + hi) // 2
        if power_at(mid) >= target_power:
            hi = mid
        else:
            lo = mid
    return hi, power_at(hi)


# ---------------------------------------------------------------------------
# Common return-shape builder
# ---------------------------------------------------------------------------


def _build_result(
    *,
    method_id: str,
    chapter: str,
    solve_for: str,
    test: str,
    n: int,
    achieved_power: float,
    inputs_echo: dict[str, Any],
    n_sims: int,
    seed: int,
    citations: list[str] | None = None,
) -> dict[str, Any]:
    ci_half = 1.96 * math.sqrt(
        max(achieved_power * (1.0 - achieved_power), 0.0) / n_sims
    )
    return {
        "method_id": method_id,
        "solve_for": solve_for,
        "test": test,
        "n": n,
        "achieved_power": achieved_power,
        "stochastic": True,
        "n_sims": n_sims,
        "seed": seed,
        "inputs_echo": inputs_echo,
        "citations": citations if citations is not None else [
            f"Fisher z-transform simulation for {chapter}.",
            "Kendall, M. & Gibbons, J. D. (1990). Rank Correlation Methods, "
            "5th Edition. Oxford University Press, New York.",
            "Devroye, L. (1986). Non-Uniform Random Variate Generation. "
            "Springer-Verlag, New York.",
        ],
        "notes": (
            f"Monte-Carlo estimate; achieved_power is stochastic. With "
            f"n_sims={n_sims}, the 95% binomial CI half-width is ~{ci_half:.4f}."
        ),
    }


# ---------------------------------------------------------------------------
# Public solvers
# ---------------------------------------------------------------------------


def _solve_single(
    *,
    test: str,
    method_id: str,
    chapter: str,
    r: float,
    rho0: float,
    dist_x: str,
    dist_y: str,
    df_x: float | None,
    df_y: float | None,
    alpha: float,
    sides: int,
    n: int | None,
    power: float | None,
    n_sims: int,
    seed: int,
    solve_for: str | None,
) -> dict[str, Any]:
    _validate_inputs(r, rho0, alpha, sides, dist_x, dist_y)

    have_n = n is not None
    have_power = power is not None
    if not (have_n or have_power):
        raise ValueError("supply at least one of (n, power)")
    if solve_for is None:
        solve_for = "n" if not have_n else "power"

    if solve_for == "power":
        assert n is not None
        achieved = _simulate_power(
            test=test, n=int(n), r=r, rho0=rho0,
            dist_x=dist_x, dist_y=dist_y, df_x=df_x, df_y=df_y,
            alpha=alpha, sides=sides, n_sims=n_sims, seed=seed,
        )
        n_out = int(n)
    elif solve_for == "n":
        assert power is not None
        n_out, achieved = _bisect_n(
            test=test, r=r, rho0=rho0,
            dist_x=dist_x, dist_y=dist_y, df_x=df_x, df_y=df_y,
            alpha=alpha, sides=sides,
            target_power=float(power), n_sims=n_sims, seed=seed,
        )
    else:
        raise ValueError(f"unsupported solve_for: {solve_for!r}")

    inputs_echo = {
        "r": r, "rho0": rho0,
        "dist_x": dist_x, "dist_y": dist_y,
        "df_x": df_x, "df_y": df_y,
        "alpha": alpha, "sides": sides,
        "n": n, "power": power,
        "n_sims": n_sims, "seed": seed,
    }
    return _build_result(
        method_id=method_id, chapter=chapter, solve_for=solve_for,
        test=test, n=n_out, achieved_power=achieved,
        inputs_echo=inputs_echo, n_sims=n_sims, seed=seed,
    )


def pearson_correlation_simulation(
    *,
    r: float,
    rho0: float = 0.0,
    dist_x: str = "normal",
    dist_y: str = "normal",
    df_x: float | None = None,
    df_y: float | None = None,
    alpha: float = 0.05,
    sides: int = 2,
    n: int | None = None,
    power: float | None = None,
    n_sims: int = 10000,
    seed: int = 42,
    solve_for: str | None = None,
) -> dict[str, Any]:
    """Pearson product-moment correlation test, simulation-based power.

    Tests H0: rho = ``rho0`` vs H1: rho != ``rho0`` (or one-sided when
    ``sides=1``). Under ``rho0 == 0`` the exact reference is Student-t
    with ``n - 2`` df; for ``rho0 != 0`` the Fisher z-transform with
    SE = 1/sqrt(n-3) is used.

    Pass either ``n`` (-> solve for power) or ``power`` (-> bisect ``n``).
    ``achieved_power`` is a Monte-Carlo estimate; the binomial 95%
    half-width is reported in ``notes``. ``seed=42`` for reproducibility.
    """
    return _solve_single(
        test="pearson",
        method_id="pearson_correlation_simulation",
        chapter="Pearson's Correlation Tests (Simulation)",
        r=r, rho0=rho0,
        dist_x=dist_x, dist_y=dist_y, df_x=df_x, df_y=df_y,
        alpha=alpha, sides=sides,
        n=n, power=power,
        n_sims=n_sims, seed=seed,
        solve_for=solve_for,
    )


def spearman_correlation_simulation(
    *,
    r: float,
    dist_x: str = "normal",
    dist_y: str = "normal",
    df_x: float | None = None,
    df_y: float | None = None,
    alpha: float = 0.05,
    sides: int = 2,
    n: int | None = None,
    power: float | None = None,
    n_sims: int = 10000,
    seed: int = 42,
    solve_for: str | None = None,
) -> dict[str, Any]:
    """Spearman's rank correlation test, simulation-based power.

    Tests H0: rho_s = 0 vs H1: rho_s != 0 using the Student-t
    approximation ``t = rs sqrt(n-2)/sqrt(1-rs^2)`` with ``n - 2`` df
    (valid for ``n >= 19``; see Bonett & Wright 2000).

    Note: ``r`` is the *Pearson product-moment* correlation of the
    underlying (X, Y) population, not Spearman's rho on the ranks;
    The simulation distributions
    are parameterised by Pearson correlation.
    """
    return _solve_single(
        test="spearman",
        method_id="spearman_correlation_simulation",
        chapter="Spearman's Rank Correlation Tests (Simulation)",
        r=r, rho0=0.0,
        dist_x=dist_x, dist_y=dist_y, df_x=df_x, df_y=df_y,
        alpha=alpha, sides=sides,
        n=n, power=power,
        n_sims=n_sims, seed=seed,
        solve_for=solve_for,
    )


def kendall_tau_b_simulation(
    *,
    r: float,
    dist_x: str = "normal",
    dist_y: str = "normal",
    df_x: float | None = None,
    df_y: float | None = None,
    alpha: float = 0.05,
    sides: int = 2,
    n: int | None = None,
    power: float | None = None,
    n_sims: int = 10000,
    seed: int = 42,
    solve_for: str | None = None,
) -> dict[str, Any]:
    """Kendall's tau-b correlation test, simulation-based power.

    Tests H0: tau = 0 vs H1: tau != 0 using the large-sample normal
    approximation with ``Var(tau) = 2(2n+5)/(9 n (n-1))``.

    Note: ``r`` is the *Pearson* correlation of the underlying (X, Y)
    population.
    """
    return _solve_single(
        test="kendall",
        method_id="kendall_tau_b_simulation",
        chapter="Kendall's Tau-b Correlation Tests (Simulation)",
        r=r, rho0=0.0,
        dist_x=dist_x, dist_y=dist_y, df_x=df_x, df_y=df_y,
        alpha=alpha, sides=sides,
        n=n, power=power,
        n_sims=n_sims, seed=seed,
        solve_for=solve_for,
    )


def power_comparison_correlation_simulation(
    *,
    r: float,
    rho0: float = 0.0,
    dist_x: str = "normal",
    dist_y: str = "normal",
    df_x: float | None = None,
    df_y: float | None = None,
    alpha: float = 0.05,
    sides: int = 2,
    n: int | None = None,
    power: float | None = None,
    n_sims: int = 10000,
    seed: int = 42,
    solve_for: str | None = None,
) -> dict[str, Any]:
    """Power comparison of Pearson, Spearman, Kendall correlation tests.

    Generates bivariate (X, Y) samples with target Pearson correlation
    ``r`` and runs all three correlation tests on the *same* simulated
    data, returning each test's rejection proportion as ``pearson_power``,
    ``spearman_power``, and ``kendall_power``.

    ``achieved_power`` reports the Pearson power for backwards
    compatibility with the single-test return shape; the per-test powers
    are in the top-level keys.

    Sample-size mode bisects on Pearson power (the most powerful of the
    three under bivariate normality), then reports all three powers at
    the chosen ``n``.
    """
    _validate_inputs(r, rho0, alpha, sides, dist_x, dist_y)

    have_n = n is not None
    have_power = power is not None
    if not (have_n or have_power):
        raise ValueError("supply at least one of (n, power)")
    if solve_for is None:
        solve_for = "n" if not have_n else "power"

    if solve_for == "power":
        assert n is not None
        n_out = int(n)
    elif solve_for == "n":
        assert power is not None
        n_out, _ = _bisect_n(
            test="pearson", r=r, rho0=rho0,
            dist_x=dist_x, dist_y=dist_y, df_x=df_x, df_y=df_y,
            alpha=alpha, sides=sides,
            target_power=float(power), n_sims=n_sims, seed=seed,
        )
    else:
        raise ValueError(f"unsupported solve_for: {solve_for!r}")

    powers = _simulate_all_three(
        n=n_out, r=r, rho0=rho0,
        dist_x=dist_x, dist_y=dist_y, df_x=df_x, df_y=df_y,
        alpha=alpha, sides=sides, n_sims=n_sims, seed=seed,
    )

    inputs_echo = {
        "r": r, "rho0": rho0,
        "dist_x": dist_x, "dist_y": dist_y,
        "df_x": df_x, "df_y": df_y,
        "alpha": alpha, "sides": sides,
        "n": n, "power": power,
        "n_sims": n_sims, "seed": seed,
    }
    ci_half = 1.96 * math.sqrt(
        max(powers["pearson_power"] * (1.0 - powers["pearson_power"]), 0.0)
        / n_sims
    )
    return {
        "method_id": "power_comparison_correlation_simulation",
        "solve_for": solve_for,
        "n": n_out,
        "achieved_power": powers["pearson_power"],
        "pearson_power": powers["pearson_power"],
        "spearman_power": powers["spearman_power"],
        "kendall_power": powers["kendall_power"],
        "stochastic": True,
        "n_sims": n_sims,
        "seed": seed,
        "inputs_echo": inputs_echo,
        "citations": [
            "Kendall, M. & Gibbons, J. D. (1990). Rank Correlation Methods, "
            "5th Edition. Oxford University Press, New York.",
            "Zar, J. H. (1984). Biostatistical Analysis, 2nd Edition. "
            "Prentice-Hall, Englewood Cliffs, New Jersey.",
        ],
        "notes": (
            f"Monte-Carlo estimate; per-test powers are stochastic. With "
            f"n_sims={n_sims}, the 95% binomial CI half-width on Pearson "
            f"power is ~{ci_half:.4f}."
        ),
    }
