#!/usr/bin/env python3
"""Generate (or check) docs/METHOD_COVERAGE.md from the method registry.

The coverage matrix is derived entirely from
``samplesize/registry/methods.json`` plus the worked-example fixtures under
``tests/validation/fixtures/`` so it can never silently drift from the code.

Usage::

    python scripts/gen_method_coverage.py          # rewrite the doc
    python scripts/gen_method_coverage.py --check   # CI: fail if out of date

In ``--check`` mode the script also verifies that the headline method and
fixture counts embedded in README.md and docs/index.md match the registry,
so every place that quotes a total stays in sync.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "samplesize" / "registry" / "methods.json"
FIXTURES = ROOT / "tests" / "validation" / "fixtures"
COVERAGE_DOC = ROOT / "docs" / "METHOD_COVERAGE.md"

# Curated caveats that are not derivable from the registry.  Keep short.
NOTES = [
    "Pearson correlation uses the exact Guenther/Hotelling density "
    "(₂F₁ + numerical integration); a `fisher-z` backend is retained "
    "for the textbook approximation.",
    "Equivalence/TOST means tests use a central-t formulation that matches "
    "the exact bivariate-noncentral-t method at moderate-to-large N but is "
    "conservative at very small N (documented per fixture).",
    "`kappa_two_raters_binary` uses the Fleiss-Cohen-Everitt variance "
    "maximised over tables (Flack et al. 1988 conservative approach).",
]

STATUS = {
    (True, True): "\U0001f7e2",   # implemented + validated
    (True, False): "\U0001f7e1",  # implemented, not validated
    (False, False): "⚪",      # not implemented
    (False, True): "⚪",
}


def _fixture_counts() -> dict[str, int]:
    """Map method-id -> number of worked examples (active fixtures only)."""
    import yaml

    counts: dict[str, int] = {}
    for yml in sorted(FIXTURES.glob("*.yaml")):
        if yml.name.startswith("_"):
            continue
        doc = yaml.safe_load(yml.read_text()) or {}
        method = doc.get("method")
        if method:
            counts[method] = counts.get(method, 0) + len(doc.get("examples", []))
    return counts


def generate() -> tuple[str, int, int, int]:
    """Return (markdown, n_methods, n_validated, n_examples)."""
    methods = json.loads(REGISTRY.read_text())
    fx = _fixture_counts()

    n_methods = len(methods)
    n_validated = sum(1 for m in methods if m.get("validated"))
    n_examples = sum(fx.values())
    n_fixture_files = len([f for f in FIXTURES.glob("*.yaml")
                           if not f.name.startswith("_")])

    # group by category, sorted
    by_cat: dict[str, list[dict]] = {}
    for m in methods:
        by_cat.setdefault(m.get("category") or "Uncategorized", []).append(m)

    lines: list[str] = []
    lines.append("<!-- GENERATED by scripts/gen_method_coverage.py "
                 "- do not edit by hand. -->")
    lines.append("# Method Coverage")
    lines.append("")
    lines.append("Auto-generated from `samplesize/registry/methods.json` and the "
                 "worked-example fixtures. Run `python scripts/gen_method_coverage.py` "
                 "to refresh; CI fails if it is out of date.")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    all_green = "all \U0001f7e2" if n_validated == n_methods else "partial"
    lines.append(f"- **{n_methods}** methods in the registry")
    lines.append(f"- **{n_validated}** validated against reference worked examples "
                 f"({all_green})")
    lines.append(f"- **{n_examples}** worked-example fixtures across "
                 f"{n_fixture_files} fixture files")
    lines.append("")
    lines.append("## Legend")
    lines.append("")
    lines.append("- ⚪ Not implemented")
    lines.append("- \U0001f7e1 Implemented, not validated against reference examples")
    lines.append("- \U0001f7e2 Implemented and validated to documented tolerance")
    lines.append("")
    lines.append("## Methods by category")
    lines.append("")
    for cat in sorted(by_cat):
        rows = sorted(by_cat[cat], key=lambda m: m["id"])
        lines.append(f"### {cat}")
        lines.append("")
        lines.append("| id | name | status | fixtures |")
        lines.append("|---|---|---|---|")
        for m in rows:
            status = STATUS[(bool(m.get("implemented")), bool(m.get("validated")))]
            n_fx = fx.get(m["id"], 0)
            lines.append(f"| `{m['id']}` | {m['name']} | {status} | {n_fx} |")
        lines.append("")

    lines.append("## Notes")
    lines.append("")
    for note in NOTES:
        lines.append(f"- {note}")
    lines.append("")
    return "\n".join(lines), n_methods, n_validated, n_examples


def _check_headline_counts(n_methods: int, n_examples: int) -> list[str]:
    """Return a list of drift errors for README.md / docs/index.md counts."""
    errors: list[str] = []
    for rel in ("README.md", "docs/index.md"):
        text = (ROOT / rel).read_text()
        if not re.search(rf"\b{re.escape(str(n_methods))}\b", text):
            errors.append(f"{rel}: current method count {n_methods} not found "
                          f"(stale total?)")
        if not re.search(rf"\b{re.escape(str(n_examples))}\b", text):
            errors.append(f"{rel}: current fixture count {n_examples} not found "
                          f"(stale total?)")
    return errors


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the doc or headline counts are stale")
    args = ap.parse_args()

    content, n_methods, n_validated, n_examples = generate()

    if args.check:
        errors: list[str] = []
        current = COVERAGE_DOC.read_text() if COVERAGE_DOC.exists() else ""
        if current != content:
            errors.append("docs/METHOD_COVERAGE.md is out of date; run "
                          "`python scripts/gen_method_coverage.py`")
        errors.extend(_check_headline_counts(n_methods, n_examples))
        if errors:
            print("Method-coverage drift detected:", file=sys.stderr)
            for e in errors:
                print(f"  - {e}", file=sys.stderr)
            return 1
        print(f"Method coverage up to date "
              f"({n_methods} methods, {n_validated} validated, "
              f"{n_examples} fixtures).")
        return 0

    COVERAGE_DOC.write_text(content)
    print(f"Wrote {COVERAGE_DOC.relative_to(ROOT)} "
          f"({n_methods} methods, {n_validated} validated, {n_examples} fixtures).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
